-- 否认工单 文件预处理表
CREATE TABLE T_B_FILE_PROC
(
    HANDLEID CHAR(32) NOT NULL,
    FILEID   VARCHAR2(32),
    PATH     VARCHAR2(256),
    FILENAME VARCHAR2(32),
    STATUS   CHAR(1),
    IN_DATE  CHAR(8),
    IN_TIME  CHAR(6)
);
-- Add comments to the table
COMMENT ON TABLE T_B_FILE_PROC
    IS '文件预处理表';
-- Add comments to the columns
COMMENT ON COLUMN T_B_FILE_PROC.HANDLEID
    IS '操作ID';
COMMENT ON COLUMN T_B_FILE_PROC.FILEID
    IS '文件ID';
COMMENT ON COLUMN T_B_FILE_PROC.PATH
    IS '文件路径';
COMMENT ON COLUMN T_B_FILE_PROC.FILENAME
    IS '文件名称';
COMMENT ON COLUMN T_B_FILE_PROC.STATUS
    IS '文件状态，0-上传；1-下载；2-删除';
COMMENT ON COLUMN T_B_FILE_PROC.IN_DATE
    IS '数据插入日期';
COMMENT ON COLUMN T_B_FILE_PROC.IN_TIME
    IS '数据插入时间';
-- Create/Recreate primary, unique and foreign key constraints
ALTER TABLE T_B_FILE_PROC
    ADD CONSTRAINT PK_FILE_PROC_ID PRIMARY KEY (HANDLEID);

-- Create table
CREATE TABLE T_B_FILE_INFO
(
    FILEID   VARCHAR2(32) NOT NULL,
    FILEPATH VARCHAR2(256),
    IN_DATE  CHAR(8),
    IN_TIME  CHAR(6),
    FILENAME VARCHAR2(256),
    FILEDATE CHAR(8),
    MER_ID   CHAR(15)
);
-- Add comments to the table
COMMENT ON TABLE T_B_FILE_INFO
    IS '上传文件信息表';
-- Add comments to the columns
COMMENT ON COLUMN T_B_FILE_INFO.FILEID
    IS '文件ID';
COMMENT ON COLUMN T_B_FILE_INFO.FILEPATH
    IS '文件保存路径';
COMMENT ON COLUMN T_B_FILE_INFO.IN_DATE
    IS '文件上传日期';
COMMENT ON COLUMN T_B_FILE_INFO.IN_TIME
    IS '文件上传时间';
COMMENT ON COLUMN T_B_FILE_INFO.FILENAME
    IS '文件名称';
COMMENT ON COLUMN T_B_FILE_INFO.FILEDATE
    IS '文件日期';
COMMENT ON COLUMN T_B_FILE_INFO.MER_ID
    IS '商户号';
ALTER TABLE T_B_FILE_INFO
    ADD CONSTRAINT PK_T_B_FILE_INFO_ID PRIMARY KEY (FILEID);